runtime: python310

env_variables:
  DEBUG: ${DEBUG}
  SECRET_KEY: ${SECRET_KEY}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}
  API_KEY: ${API_KEY}
  USERNAME: ${USERNAME}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

handlers:runtime: python310  

env_variables:
  DEBUG: ${DEBUG}  
  SECRET_KEY: ${SECRET_KEY}
  DATABASE_NAME: ${DATABASE_NAME}  
  DATABASE_USER: ${DATABASE_USER} 
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}  
  DATABASE_HOST: ${DATABASE_HOST}  
  DATABASE_PORT: ${DATABASE_PORT}  
  API_KEY: ${API_KEY} 
  USERNAME: ${USERNAME}  
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}  
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}  

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

- url: /static
  static_dir: static/

- url: /.*
  script: auto
